version: '3.8'

services:
  php:
    build: .                        # buidling the image from Dockerfile
    ports:
      - "8080:80"                   # map localhost:8080 to container:80(inside Docker container)
    volumes:
      - .:/var/www/html             
